# Generated by Django 3.0.3 on 2020-03-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credential',
            field=models.TextField(default='My credentials are'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interest',
            field=models.TextField(default='My interest are'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Name', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='reference',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
