# Generated by Django 3.0.3 on 2020-03-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0002_auto_20200330_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.CharField(default='firstName', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.CharField(default='lastName', max_length=50),
        ),
    ]
